name: ipfs
description: A starting point for Dart libraries or applications.
version: 1.0.3
homepage: https://github.com/AIDXNZ

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  path: ^1.6.0


dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

  build_runner:
  
  chopper_generator: 
