name: ipfs
description: A starting point for Dart libraries or applications.
version: 1.0.3
homepage: https://github.com/AIDXNZ

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  dio: ^2.1.16
  path: ^1.6.0

  grpc: ^2.1.3
  protobuf: ^1.0.1

  chopper: ^3.0.1+1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

  build_runner:
  
  chopper_generator: 
